### ISSUE TITLE
送付先住所の登録を促す必要有り

### ISSUE THREAD

**Issue by yasmaimo** [webcamp-tozai/TOZAI-ECsite#81]
ordersテーブルのaddress_idには、存在するレコードのidを必ず入れなければなりません。よって、送付先住所が未登録のユーザーは購入前に登録を促す必要があります。

**Comment by yasmaimo** [comment]
ordersテーブルのaddress_idに、存在するレコードのIDを入れないと購入が出来ません。そのため、送付先住所が未登録の場合は購入前に登録を促すようにしなければなりません。

**Comment by FYoshi0118** [comment]
ユーザー新規登録時に送付先住所に登録されるように変更済み
user#resistrationに書いてます
